# Generated by Django 3.1.7 on 2021-04-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfWorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Worm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('exp_name', models.CharField(max_length=16)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bt.typesofworm')),
            ],
        ),
        migrations.CreateModel(
            name='ParametsWorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('worm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bt.worm')),
            ],
        ),
    ]
