# Generated by Django 3.1.7 on 2021-04-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0002_parametsworm_typesofworm_worm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametsWorm',
            new_name='ParametrsWorm',
        ),
    ]
