# Generated by Django 3.1.7 on 2021-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0003_auto_20210405_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTypesOfWorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
