# Generated by Django 3.1.7 on 2021-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0004_subtypesofworm'),
    ]

    operations = [
        migrations.AddField(
            model_name='worm',
            name='sub_type',
            field=models.ManyToManyField(blank=True, null=True, to='bt.SubTypesOfWorm'),
        ),
    ]
