# Generated by Django 3.1.7 on 2021-05-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_life', '0002_auto_20210518_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('pics', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_life.book')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('copies', models.IntegerField()),
                ('students', models.IntegerField()),
                ('departments', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='studentinroom',
            name='student',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentInRoom',
        ),
        migrations.AddField(
            model_name='bookinlib',
            name='lib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_life.library'),
        ),
    ]
