# Generated by Django 3.1.7 on 2021-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_life', '0003_auto_20210518_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='library',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='library',
            name='students',
        ),
        migrations.AddField(
            model_name='bookinlib',
            name='copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinlib',
            name='departments',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='bookinlib',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
